### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by JayenLee** [wangsijie/express-aliyun-log#1]
根据例子编写
const logger = require("express-aliyun-log");
logger(app, opt);
但是报这个错误
ReferenceError: maxBodyLength is not defined
    at module.exports (/Users/Barnett/app/apigateway/node_modules/express-aliyun-log/lib/index.js:14:24)
    at Object.<anonymous> (/Users/Barnett/app/apigateway/app.js:33:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)

**Comment by wangsijie** [comment]
需要指定options🚀
